User interface
barakadanny/School-library-Ruby pull request #4
Opened 2022-11-18 16:53 UTC by barakadanny

In this PR I create a form of UI for the school library app

2022-11-18 20:01 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @barakadanny,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍 
✅ Linter checks passed 👍 
✅ App UI looks nice 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-11-18 20:01 UTC, AmaduKamara commented on app.rb
> +  end
- [ ] This method is not working properly as it should. When creating a student, as soon as I enter either lowercase y or uppercase Y for parent permission, the app crashes with the error below in the screenshot:

![image](https://user-images.githubusercontent.com/50941074/202791027-5e52c46b-4645-4a33-9adf-0b54a1c08635.png)

- [ ] Kindly work on it so a student is created successfully. I couldn't check on the rental for a person because a person has to be created first before creating a rental for a person. Kindly check all features and see if all work before sending for a review 👍

2022-11-18 20:01 UTC, AmaduKamara commented on app.rb
> +  end
- [ ] When creating a teacher, the app crashes when entering specialization for a teacher. Kindly work on that so a teacher is created successfully. Check the screenshot below for details on the error 👍 

![image](https://user-images.githubusercontent.com/50941074/202792115-86cda761-c602-45b0-98ea-5c06c1f630c2.png)

2022-11-19 11:18 UTC, Ismailco approved these changes
### Hi @barakadanny, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-19 11:18 UTC, Ismailco commented on app.rb
> +  def create_rental
- [ ] [OPTIONAL] When creating a rental, the app crashes when entering the date. Kindly work on that so a rental is created successfully.
![Screenshot_20221119_121725](https://user-images.githubusercontent.com/25227022/202848040-41fa6cd1-165e-458e-b876-f774163f629f.png)

2022-11-19 11:26 UTC, merged